# Generated by Django 3.0.7 on 2020-10-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
