# Generated by Django 3.1 on 2020-09-14 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.IntegerField(choices=[(1, 'mock exam'), (2, 'Quiz'), (3, 'Case Study')])),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.lecturer'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.lecturer'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='student',
            field=models.ManyToManyField(null=True, to='Admin.Student'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.account'),
        ),
        migrations.AlterField(
            model_name='student',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.account'),
        ),
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.courses')),
                ('student', models.ManyToManyField(to='Admin.Student')),
            ],
        ),
    ]
