# Generated by Django 3.1 on 2020-09-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_auto_20200914_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='student',
            field=models.ManyToManyField(to='Admin.Student'),
        ),
    ]
