# Generated by Django 3.0.7 on 2020-10-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_auto_20201030_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(choices=[('Foundation Level', 'Foundation Level'), ('Operational Level', 'Operational Level'), ('Management Level', 'Management Level'), ('Strategic Level', 'Strategic Level')], max_length=100),
        ),
    ]
