# Generated by Django 3.0.7 on 2020-10-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_auto_20201030_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='overview',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
