# Generated by Django 3.0.7 on 2020-10-31 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_auto_20201031_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='level_No',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='Admin.Module'),
        ),
    ]
