# Generated by Django 3.0.7 on 2020-11-03 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0024_auto_20201103_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='membership',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='Admin.Module'),
        ),
    ]
