# Generated by Django 3.1.3 on 2020-11-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0030_auto_20201123_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('created',)},
        ),
    ]
