# Generated by Django 3.1.3 on 2020-11-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0031_auto_20201123_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.RemoveField(
            model_name='course',
            name='created',
        ),
    ]
